SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DeadLockEvents]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DeadLockEvents](
	[TimeCaptured] [datetime2](7) NOT NULL,
	[DeadLockGraph] [xml] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TimeCaptured] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
